CREATE TABLE order_info (
    order_id BIGINT PRIMARY KEY,
    parent_order_id BIGINT,
    source VARCHAR(20),
    account_id BIGINT,
    client_order_id VARCHAR(256),
    exchange_id VARCHAR(50),
    exchange_order_id VARCHAR(256),
    instrument_type VARCHAR(20),
    batch_id VARCHAR(50),
    symbol VARCHAR(10),
    order_type VARCHAR(20),
    time_in_force VARCHAR(10),
    side VARCHAR(10),
    quantity DECIMAL(18,4),
    leaves_qty DECIMAL(18,4),
    cash_order_quantity DECIMAL(18,2),
    price DECIMAL(18,4),
    price_currency VARCHAR(10),
    stop_price DECIMAL(18,4),
    exec_type VARCHAR(20),
    order_status VARCHAR(20),
    transmission VARCHAR(50),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    filled_at TIMESTAMP,
    cum_qty DECIMAL(18,4)
);
